// <auto-generated />
namespace MCCWebApps.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addmodel3table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmodel3table));
        
        string IMigrationMetadata.Id
        {
            get { return "202007070331426_addmodel3table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
